<?php
// $Id: notifications_nice.module,v 1.1.2.3.2.1 2010/04/29 09:09:22 jareyero Exp $

/**
 * @file
 * Nice js widget for subscriptions
 *
 * Module written by Jose A. Reyero, Development Seed.
 *
 * Idea and code by Moshe Weitzman, from http://groups.drupal.org/node/17779
 */

/**
 * Implementation of hook_link().
 */
function notifications_nice_link($type, $node = NULL, $teaser = FALSE) {
  global $user;

  if ($type == 'node' && !$teaser && ($node_links = notifications_nice_node_links($node)) ) {
    notifications_nice_addons();
    $links['nice_links'] = array(
      'title' => notifications_nice_links($node_links),
      'html' => TRUE,
    );
    return $links;
  }
}

/**
 * Get node links checking subscription types and permissions
 */
function notifications_nice_node_links($node) {
  global $user;

  if (notifications_access_subscribe($user)) {
    notifications_include('object.inc');
    return notifications_object_subscribe_links('node', $node);
  }  
}

/**
 * Format links block
 */
function notifications_nice_links($links) {
  // Visible part
  $title = t('Subscriptions');
  $output = '<a title="' . $title . '" href="#node_subscription_links" rel="#node_subscription_links" class="load-local">';
  $src = base_path() . drupal_get_path('module', 'notifications_nice') . '/button_subscriptions.gif';
  $output .= "<img src=\"$src\" alt=\"$title\" width=\"138\" height=\"41\">";
  $output .= "</a>\n";
  // Hidden part
  $output .= '<div id="node_subscription_links" style="display:none">';
  $output .= theme('links', $links);
  $output .= "</div>\n";
  return $output;
}

/**
 * Load needed CSS and JS stuff
 */
function notifications_nice_addons() {
  $module = drupal_get_path('module', 'notifications_nice');
  $cluetip = $module . '/cluetip';
  // Cluetip elements
  drupal_add_css($cluetip . '/jquery.cluetip.css');
  drupal_add_js($cluetip . '/jquery.cluetip.js');
  drupal_add_js($cluetip . '/lib/jquery.hoverIntent.js');
  // Add own module elements
  drupal_add_js($module . '/notifications_nice.js');
  drupal_add_css($module . '/notifications_nice.css');
}
